export const last20StatsMap = {
  c2: 'averageKDRatio',
  c3: 'averageKRRatio',
  c4: 'averageHeadshots',
  i6: 'averageKills',
  i9: 'totalMVPs',
  i13: 'totalHeadshots',
  i14: 'totalTripleKills',
  i15: 'totalQuadroKills',
  i16: 'totalPentaKills',
};

export const averageStatsMap = {
  k1: 'averageKills',
  k2: 'averageDeaths',
  k3: 'averageAssists',
  k4: 'averageMVPs',
  k5: 'averageKDRatio',
  k6: 'winRate',
  k8: 'averageHeadshots',
  k9: 'averageKRRatio',
  k10: 'averageTripleKills',
  k11: 'averageQuadroKills',
  k12: 'averagePentaKills',
  m1: 'totalMatches',
  m2: 'totalWins',
  m3: 'totalKills',
  m4: 'totalDeaths',
  m5: 'totalAssists',
  m6: 'totalMVPs',
  m7: 'totalKDRatio',
  m8: 'totalRounds',
  m9: 'totalHeadshots',
  m10: 'totalTripleKills',
  m11: 'totalQuadroKills',
  m12: 'totalPentaKills',
};
